- Ficher source : communes-france-2025.csv
- Fichier de sorti : stg_gouv_communes.csv
- Date de création : 13/11/2025
- Dernière modification : 17/11/2025

- Version(s) : 
    - 1 - 13/11/2025 : Nettoyage du fichier et création du csv "gouv_communes"
    - 2 - 17/11/2025 : Renommage du fichier et création du csv "stg_gouv_communes"

In [1]:
#Librairie(s) utilisée(s)
import pandas as pd

In [2]:
#Création du dataframe à partir du fichier csv
df = pd.read_csv(r'C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\01_data\01_data_bronze\communes-france-2025.csv',
                 encoding= "UTF-8")
df.head()

C:\Users\justi\AppData\Local\Temp\ipykernel_13224\1196045354.py:2: DtypeWarning: Columns (1,12,14,16,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\01_data\01_data_bronze\communes-france-2025.csv',

,Unnamed: 0,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,...,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve
0,0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,...,4.921,46.153,4.926,6,Rural à habitat dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,COM,commune,...,5.423,46.009,5.428,6,Rural à habitat dispersé,0.0,communes non pôle,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,COM,commune,...,5.360,45.961,5.373,2,Centres urbains intermédiaires,3.0,centres structurants d'équipements et de services,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,COM,commune,...,4.903,45.996,4.912,5,Bourgs ruraux,1.0,centres locaux d'équipements et de services,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,COM,commune,...,5.601,45.750,5.594,6,Rural à habitat dispersé,0.0,communes non pôle,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon

In [3]:
df.shape

(34935, 47)

In [4]:
df.count()

Unnamed: 0                           34935
code_insee                           34935
nom_standard                         34935
nom_sans_pronom                      34935
nom_a                                34935
nom_de                               34935
nom_sans_accent                      34935
nom_standard_majuscule               34935
typecom                              34935
typecom_texte                        34935
reg_code                             34935
reg_nom                              34935
dep_code                             34935
dep_nom                              34935
canton_code                          34879
canton_nom                           34879
epci_code                            34932
epci_nom                             34932
academie_code                        34935
academie_nom                         34935
code_postal                          34932
codes_postaux                        34932
zone_emploi                          34932
code_insee_centre_zone_emploi        34803
code_unite_urbaine                   34932
nom_unite_urbaine                     7576
taille_unite_urbaine                 34932
type_commune_unite_urbaine           34932
statut_commune_unite_urbaine         34932
population                           34935
superficie_hectare                   34935
superficie_km2                       34935
densite                              34932
altitude_moyenne                     34935
altitude_minimale                    34935
altitude_maximale                    34935
latitude_mairie                      34935
longitude_mairie                     34935
latitude_centre                      34926
longitude_centre                     34926
grille_densite                       34935
grille_densite_texte                 34935
niveau_equipements_services          34803
niveau_equipements_services_texte    34803
gentile                              24065
url_wikipedia                        34878
url_villedereve                      34935
dtype: int64

In [5]:
df.count().isna() # Pas de données manquantes

Unnamed: 0                           False
code_insee                           False
nom_standard                         False
nom_sans_pronom                      False
nom_a                                False
nom_de                               False
nom_sans_accent                      False
nom_standard_majuscule               False
typecom                              False
typecom_texte                        False
reg_code                             False
reg_nom                              False
dep_code                             False
dep_nom                              False
canton_code                          False
canton_nom                           False
epci_code                            False
epci_nom                             False
academie_code                        False
academie_nom                         False
code_postal                          False
codes_postaux                        False
zone_emploi                          False
code_insee_centre_zone_emploi        False
code_unite_urbaine                   False
nom_unite_urbaine                    False
taille_unite_urbaine                 False
type_commune_unite_urbaine           False
statut_commune_unite_urbaine         False
population                           False
superficie_hectare                   False
superficie_km2                       False
densite                              False
altitude_moyenne                     False
altitude_minimale                    False
altitude_maximale                    False
latitude_mairie                      False
longitude_mairie                     False
latitude_centre                      False
longitude_centre                     False
grille_densite                       False
grille_densite_texte                 False
niveau_equipements_services          False
niveau_equipements_services_texte    False
gentile                              False
url_wikipedia                        False
url_villedereve                      False
dtype: bool

In [6]:
df.dtypes

Unnamed: 0                             int64
code_insee                            object
nom_standard                          object
nom_sans_pronom                       object
nom_a                                 object
nom_de                                object
nom_sans_accent                       object
nom_standard_majuscule                object
typecom                               object
typecom_texte                         object
reg_code                               int64
reg_nom                               object
dep_code                              object
dep_nom                               object
canton_code                           object
canton_nom                            object
epci_code                             object
epci_nom                              object
academie_code                          int64
academie_nom                          object
code_postal                          float64
codes_postaux                         object
zone_emploi                          float64
code_insee_centre_zone_emploi         object
code_unite_urbaine                    object
nom_unite_urbaine                     object
taille_unite_urbaine                 float64
type_commune_unite_urbaine            object
statut_commune_unite_urbaine          object
population                             int64
superficie_hectare                     int64
superficie_km2                         int64
densite                              float64
altitude_moyenne                       int64
altitude_minimale                    float64
altitude_maximale                    float64
latitude_mairie                      float64
longitude_mairie                     float64
latitude_centre                      float64
longitude_centre                     float64
grille_densite                         int64
grille_densite_texte                  object
niveau_equipements_services          float64
niveau_equipements_services_texte     object
gentile                               object
url_wikipedia                         object
url_villedereve                       object
dtype: object

In [7]:
# Filtrage pour garder le département de l'Ille-et-Vilaine et identification des colonnes à conserver
mask= (df['code_insee'].str[:2] == "35")
cols =['code_insee', 'nom_standard', 'codes_postaux', 'canton_code', 'canton_nom', 'superficie_hectare', 'superficie_km2', 'latitude_centre', 'longitude_centre']

df= df.loc[mask, cols]
df.head()

,code_insee,nom_standard,codes_postaux,canton_code,canton_nom,superficie_hectare,superficie_km2,latitude_centre,longitude_centre
13170,35001,Acigné,"35538, 35690",3513,Liffré,3015,30,48.146,-1.519
13171,35002,Amanlis,35150,3512,Janzé,2557,26,48.000,-1.496
13172,35003,Andouillé-Neuville,35250,3501,Val-Couesnon,1268,13,48.298,-1.596
13173,35004,Val-Couesnon,"35560, 35460",3501,Val-Couesnon,942,9,48.462,-1.479
13174,35005,Arbrissel,35130,3510,La Guerche-de-Bretagne,460,5,47.927,-1.295

In [8]:
# Création de la colonne 'MVP' pour cibler les communes cibles et filtrer le dataset dessus
MVP = [35032, 35058, 35196, 35065, 35275, 35144, 35266, 35315, 35278, 35245, 35208, 35353, 35120, 35210, 35352, 35059, 35250, 35079, 35363, 35051, 35055, 35076, 35189, 35066, 35204, 35022, 35351, 35088, 35080, 35131, 35001, 35206, 35081, 35139, 35334, 35216, 35024, 35240, 35039, 35047, 35281, 35180]

df['MVP'] = df['code_insee'].astype(int).apply(lambda x: 'oui' if x in MVP else 'non')

df['MVP'].describe()

count     332
unique      2
top       non
freq      290
Name: MVP, dtype: object

In [9]:
# Filtrage du dataset pour conserver que les communes de notre MVP:

mask= (df['MVP'] == 'oui')
df= df.loc[mask, cols]
df

,code_insee,nom_standard,codes_postaux,canton_code,canton_nom,superficie_hectare,superficie_km2,latitude_centre,longitude_centre
13170,35001,Acigné,"35538, 35690",3513,Liffré,3015,30,48.146,-1.519
13189,35022,Bécherel,35190,3515,Montauban-de-Bretagne,55,1,48.296,-1.943
13191,35024,Betton,"35831, 35830, 35766",3503,Betton,2673,27,48.181,-1.646
13199,35032,Bourgbarré,35230,3512,Janzé,1477,15,47.989,-1.622
13205,35039,Brécé,"35538, 35530, 35532",3513,Liffré,725,7,48.111,-1.490
13212,35047,Bruz,"35091, 35027, 35171, 35172, 35170, 35174",3504,Bruz,2977,30,48.026,-1.748
13215,35051,Cesson-Sévigné,"35576, 35517, 35510, 35513, 35913, 35512, 3551...",3503,Betton,3210,32,48.120,-1.597
13218,35055,Chantepie,"35574, 35573, 35572, 35135, 35571",3520,Rennes-3,1200,12,48.082,-1.604
13221,35058,La Chapelle-Chaussée,35630,3515,Montauban-de-Bretagne,1481,15,48.266,-1.864
13222,35059,La Chapelle-des-Fougeretz,"35768, 35520",3503,Betton,865,9,48.177,-1.741
13228,35065,La Chapelle-Thouarault,35590,3524,Le Rheu,774,8,48.125,-1.858
13229,35066,Chartres-de-Bretagne,"35131, 35091, 35176, 35177",3504,Bruz,1003,10,48.045,-1.706
13237,35076,Chavagne,35310,3524,Le Rheu,1250,12,48.056,-1.786
13240,35079,Chevaigné,35250,3503,Betton,1040,10,48.225,-1.637
13241,35080,Cintré,35310,3524,Le Rheu,845,8,48.109,-1.887
13242,35081,Clayes,35590,3514,Melesse,432,4,48.179,-1.854
13248,35088,Corps-Nuds,35150,3512,Janzé,2291,23,47.982,-1.570
13277,35120,Gévezé,"35768, 35850",3514,Melesse,2771,28,48.213,-1.799
13287,35131,L'Hermitage,35590,3524,Le Rheu,688,7,48.122,-1.817
13295,35139,Laillé,35890,3504,Bruz,3207,32,47.967,-1.714
13300,35144,Langan,35850,3515,Montauban-de-Bretagne,777,8,48.236,-1.846
13334,35180,Miniac-sous-Bécherel,35190,3515,Montauban-de-Bretagne,1358,14,48.281,-1.927
13342,35189,Montgermont,"35766, 35760, 35768",3503,Betton,461,5,48.154,-1.717
13349,35196,Mordelles,35310,3524,Le Rheu,3032,30,48.086,-1.842
13357,35204,Nouvoitou,35410,3512,Janzé,1941,19,48.030,-1.552
13359,35206,Noyal-Châtillon-sur-Seiche,35230,3504,Bruz,2644,26,48.052,-1.663
13361,35208,Orgères,35230,3512,Janzé,1676,17,47.985,-1.666
13362,35210,Pacé,"35740, 35742, 35743, 35741",3523,Rennes-6,3505,35,48.152,-1.777
13367,35216,Parthenay-de-Bretagne,35850,3514,Melesse,488,5,48.188,-1.830
13391,35240,Le Rheu,"35653, 35652, 35650, 35651",3524,Le Rheu,1917,19,48.097,-1.782
13396,35245,Romillé,35850,3515,Montauban-de-Bretagne,2898,29,48.222,-1.879
13401,35250,Saint-Armel,35230,3512,Janzé,787,8,48.013,-1.581
13416,35266,Saint-Erblon,35230,3512,Janzé,1091,11,48.019,-1.642
13423,35275,Saint-Gilles,35590,3514,Melesse,2097,21,48.152,-1.854
13426,35278,Saint-Grégoire,"35762, 35769, 35767, 35760, 35768, 35763, 3576...",3503,Betton,1757,18,48.159,-1.686
13429,35281,Saint-Jacques-de-la-Lande,"35056, 35092, 35032, 35205, 35136, 35005, 3520...",3522,Rennes-5,1230,12,48.076,-1.724
13458,35315,Saint-Sulpice-la-Forêt,35250,3513,Liffré,679,7,48.212,-1.577
13476,35334,Thorigné-Fouillard,"35235, 35236",3513,Liffré,1353,14,48.157,-1.584
13489,35351,Le Verger,35160,3524,Le Rheu,696,7,48.066,-1.937
13490,35352,Vern-sur-Seiche,"35770, 35771, 35772",3512,Janzé,1986,20,48.052,-1.605
13491,35353,Vezin-le-Coquet,"35921, 35920, 35132, 35038, 35746",3524,Le Rheu,793,8,48.117,-1.750
13501,35363,Pont-Péan,35131,3504,Bruz,875,9,48.011,-1.696

In [10]:
df.shape #Pour vérifier qu'on a bien 42 lignes, pour 42 communes

(42, 9)

In [11]:
df.isna().sum() # pour vérifier que le dataset est complet

code_insee            0
nom_standard          0
codes_postaux         0
canton_code           0
canton_nom            0
superficie_hectare    0
superficie_km2        0
latitude_centre       0
longitude_centre      0
dtype: int64

In [12]:
# Reste à renommer les colonnes et les passer au format souhaité
df.rename(columns={'code_insee' : 'code_geo', 'nom_standard' : 'nom_commune'}, inplace= True)

df['code_geo']= df['code_geo'].astype(int)

df.dtypes

code_geo                int32
nom_commune            object
codes_postaux          object
canton_code            object
canton_nom             object
superficie_hectare      int64
superficie_km2          int64
latitude_centre       float64
longitude_centre      float64
dtype: object

In [ ]:
# Exporter le dataset nettoyé en csv
df.to_csv("stg_gouv_communes.csv", sep=";", index=False, encoding='UTF-8')