
- Ficher source : tco-bus-topologie-lignes-td
- Fichier de sorti : stg_star_bus_lignes.csv
- Date de création : 13/11/2025
- Dernière modification : 17/11/2025

- Version(s) : 
    - 1 - 13/11/2025 : Nettoyage du fichier et création du csv "star_bus_lignes"
    - 2 - 17/11/2025 : Renommage du fichier et création du csv "stg_star_bus_lignes"

In [1]:
#Librairie(s) utilisée(s)
import pandas as pd

In [2]:
#Création du dataframe à partir du fichier csv
bus_lignes = pd.read_csv(r"C:\Users\justi\OneDrive\Je-deviens-Data-Analyst\JEDHA\00_Certif\bloc_6\01_data\01_data_bronze\tco-bus-topologie-lignes-td.csv"
                         , delimiter=";")
bus_lignes.head()

,Identifiant,Date de début de version,Date de fin de version,Est la version active,Nom court,Nom long,Famille commerciale,Parcours principal aller (ID),Parcours principal retour (ID),Billettique (ID),Couleur de tracé de la ligne,Couleur de texte de la ligne,Visibilité,Routeid gtfs/gtfs-rt
0,2,2024-09-02,NaN,Oui,C2,Cesson-Sévigné (Cesson - Viasilva) <> Rennes (...,CHRONOSTAR,0002-A-2131-1071,0002-B-1071-2131,2.0,#008bd2,#ffffff,Grand public,6-0002
1,5,2022-10-24,NaN,Oui,C5,Rennes (Saint-Laurent) <> Rennes (Lycée Bréqui...,CHRONOSTAR,0005-A-1103-1269,0005-B-1269-1103,5.0,#f39200,#1a171b,Grand public,6-0005
2,11,2022-10-24,NaN,Oui,11,Rennes (La Poterie) <> Vezin-le-Coquet (ZI Ouest),Urbaine,0011-A-1746-3751,0011-B-3751-1746,11.0,#004f9e,#ffffff,Grand public,6-0011
3,34,2022-10-24,NaN,Oui,34,Rennes (ZA Saint-Sulpice) <> Cesson-Sévigné <>...,Inter-quartiers,0034-A-1631-3028,0034-B-3028-1631,34.0,#f39200,#1a171b,Grand public,6-0034
4,35,2025-09-01,NaN,Oui,35,Rennes (The Land) <> Rennes (Villejean-Univers...,Inter-quartiers,0035-A-1496-1553,0035-B-1553-1496,35.0,#ef859d,#1a171b,Grand public,6-0035

In [3]:
# Nombre de lignes et de colonnes
bus_lignes.shape

(168, 14)

In [4]:
# Nombre de lignes avec valeur
bus_lignes.count()

Identifiant                       168
Date de début de version          168
Date de fin de version              2
Est la version active             168
Nom court                         168
Nom long                          168
Famille commerciale               168
Parcours principal aller (ID)     153
Parcours principal retour (ID)    151
Billettique (ID)                  152
Couleur de tracé de la ligne      168
Couleur de texte de la ligne      168
Visibilité                        168
Routeid gtfs/gtfs-rt              168
dtype: int64

In [5]:
# Valeurs manquantes
bus_lignes.isnull().sum()

Identifiant                         0
Date de début de version            0
Date de fin de version            166
Est la version active               0
Nom court                           0
Nom long                            0
Famille commerciale                 0
Parcours principal aller (ID)      15
Parcours principal retour (ID)     17
Billettique (ID)                   16
Couleur de tracé de la ligne        0
Couleur de texte de la ligne        0
Visibilité                          0
Routeid gtfs/gtfs-rt                0
dtype: int64

In [6]:
bus_lignes.columns

Index(['Identifiant', 'Date de début de version', 'Date de fin de version',
       'Est la version active', 'Nom court', 'Nom long', 'Famille commerciale',
       'Parcours principal aller (ID)', 'Parcours principal retour (ID)',
       'Billettique (ID)', 'Couleur de tracé de la ligne',
       'Couleur de texte de la ligne', 'Visibilité', 'Routeid gtfs/gtfs-rt'],
      dtype='object')

In [7]:
# Selection des colonnes utiles
keep_cols = ['Identifiant','Est la version active','Nom court', 'Famille commerciale' ]
df = bus_lignes.loc[:,keep_cols]
df.head()

   Identifiant Est la version active Nom court Famille commerciale
0            2                   Oui        C2          CHRONOSTAR
1            5                   Oui        C5          CHRONOSTAR
2           11                   Oui        11             Urbaine
3           34                   Oui        34     Inter-quartiers
4           35                   Oui        35     Inter-quartiers

In [8]:
# Vérification si tout est la version active
df['Est la version active'].unique()

array(['Oui'], dtype=object)

In [9]:
# Suppression de cette colonne
df = df.drop('Est la version active', axis=1)
df.head()

   Identifiant Nom court Famille commerciale
0            2        C2          CHRONOSTAR
1            5        C5          CHRONOSTAR
2           11        11             Urbaine
3           34        34     Inter-quartiers
4           35        35     Inter-quartiers

In [10]:
# Renommage des colonnes gardées
df.columns = ['id_ligne', 'nom_ligne', 'famille_ligne']
df.head()

   id_ligne nom_ligne    famille_ligne
0         2        C2       CHRONOSTAR
1         5        C5       CHRONOSTAR
2        11        11          Urbaine
3        34        34  Inter-quartiers
4        35        35  Inter-quartiers

In [11]:
# Vérification des types des colonnes
df.dtypes

id_ligne          int64
nom_ligne        object
famille_ligne    object
dtype: object

In [12]:
# Changement de types
df = df.astype({
    'nom_ligne': 'string',
    'famille_ligne': 'string'
})
df.dtypes

id_ligne                  int64
nom_ligne        string[python]
famille_ligne    string[python]
dtype: object

In [13]:
# Nombre de lignes au total
df['id_ligne'].nunique()

168

In [14]:
# Classer les lignes par ordre croissant d'id
df = df.sort_values(by = 'id_ligne')
df.head(30)

     id_ligne nom_ligne    famille_ligne
66          1        C1       CHRONOSTAR
0           2        C2       CHRONOSTAR
106         3        C3       CHRONOSTAR
32          4        C4       CHRONOSTAR
1           5        C5       CHRONOSTAR
67          6        C6       CHRONOSTAR
68          7        C7       CHRONOSTAR
69         10        10          Urbaine
2          11        11          Urbaine
33         12        12          Urbaine
107        13        13          Urbaine
34         14        14          Urbaine
35         32        32  Inter-quartiers
3          34        34  Inter-quartiers
4          35        35  Inter-quartiers
36         37        37  Inter-quartiers
139        38        38  Inter-quartiers
70         39        39  Inter-quartiers
37         47      C7ex       CHRONOSTAR
140        50        50   Métropolitaine
38         51        51   Métropolitaine
71         52        52   Métropolitaine
141        53        53   Métropolitaine
39         54        54   Métropolitaine
108        55        55   Métropolitaine
109        56        56   Métropolitaine
142        59        59   Métropolitaine
110        61        61   Métropolitaine
143        62        62   Métropolitaine
144        64        64   Métropolitaine

In [ ]:
# Export as a csv table
df.to_csv('stg_star_bus_lignes.csv', sep=';', index=False)